/**
 * Response utilities template generator
 * Creates helper functions for sending consistent API responses
 */

import { CodeBuilder } from '../base/code-builder.js';

export function generateResponseUtils(): string {
  const builder = new CodeBuilder();

  builder
    .comment('API Response Utilities')
    .comment('Consistent response formatting with Result pattern support')
    .line()
    .import(['Request', 'Response'], 'express')
    .import(['Result', 'isOk'], '../core/result.js')
    .import(['AppError', 'isAppError', 'InternalServerError', 'ValidationError'], '../core/errors.js')
    .import(['logger'], './logger.utils.js')
    .line()
    .section('Response Helper Functions')
    .line()
    .comment('Send success response')
    .line('export function sendSuccess<T>(')
    .line('  res: Response,')
    .line('  data: T,')
    .line('  message?: string,')
    .line('  statusCode: number = 200')
    .line('): void {')
    .line('  res.status(statusCode).json({')
    .line('    success: true,')
    .line('    message,')
    .line('    data')
    .line('  });')
    .line('}')
    .line()
    .comment('Send error response')
    .line('export function sendError(')
    .line('  res: Response,')
    .line('  error: AppError | Error,')
    .line('  statusCode?: number')
    .line('): void {')
    .line('  const appError = isAppError(error)')
    .line('    ? error')
    .line('    : InternalServerError.fromError(error);')
    .line()
    .line('  res.status(statusCode || appError.statusCode).json({')
    .line('    success: false,')
    .line('    error: appError.toJSON()')
    .line('  });')
    .line('}')
    .line()
    .comment('Send validation error')
    .line('export function sendValidationError(')
    .line('  res: Response,')
    .line('  errors: any,')
    .line('  message: string = \"Validation failed\"')
    .line('): void {')
    .line('  const validationError = new ValidationError(message, errors);')
    .line('  res.status(400).json({')
    .line('    success: false,')
    .line('    error: validationError.toJSON()')
    .line('  });')
    .line('}')
    .line()
    .comment('Send Result<T, E> - Handles Result pattern automatically')
    .line('export function sendResult<T, E extends AppError = AppError>(')
    .line('  res: Response,')
    .line('  result: Result<T, E>,')
    .line('  successMessage?: string,')
    .line('  successStatus: number = 200')
    .line('): void {')
    .line('  if (isOk(result)) {')
    .line('    sendSuccess(res, result.value, successMessage, successStatus);')
    .line('  } else {')
    .line('    sendError(res, result.error);')
    .line('  }')
    .line('}')
    .line()
    .comment('Advanced: Send response with validation + controller')
    .comment('Validates data first, then executes controller, then sends response')
    .line('export async function sendResponse<TData, TResult, TError extends AppError = AppError>(')
    .line('  req: Request,')
    .line('  res: Response,')
    .line('  options: {')
    .line('    validator: (data: unknown) => Promise<{ success: boolean; data?: TData; errors?: any }>;')
    .line('    controller: (data: TData) => Promise<Result<TResult, TError>>;')
    .line('    dataSource?: "body" | "query" | "params";')
    .line('    successMessage?: string;')
    .line('    successStatus?: number;')
    .line('  }')
    .line('): Promise<void> {')
    .line('  const { validator, controller, dataSource = "body", successMessage, successStatus = 200 } = options;')
    .line()
    .line('  try {')
    .line('    // 1. Get data from request')
    .line('    const requestData = dataSource === "body" ? req.body')
    .line('      : dataSource === "query" ? req.query')
    .line('      : req.params;')
    .line()
    .line('    // 2. Validate')
    .line('    const validationResult = await validator(requestData);')
    .line('    if (!validationResult.success) {')
    .line('      logger.warn({ method: req.method, path: req.path, errors: validationResult.errors }, "Validation failed");')
    .line('      return sendValidationError(res, validationResult.errors);')
    .line('    }')
    .line()
    .line('    // 3. Execute controller')
    .line('    const result = await controller(validationResult.data!);')
    .line()
    .line('    // 4. Send result')
    .line('    sendResult(res, result, successMessage, successStatus);')
    .line('  } catch (error) {')
    .line('    logger.error({ err: error, method: req.method, path: req.path }, "Handler error");')
    .line('    sendError(res, error as Error);')
    .line('  }')
    .line('}');

  return builder.build();
}
