/**
 * Response utilities template generator
 * Creates helper functions for sending consistent API responses with ControllerResult pattern
 */

import { CodeBuilder } from '../base/code-builder.js';

export function generateResponseUtils(): string {
  const builder = new CodeBuilder();

  builder
    .comment('API Response Utilities')
    .comment('Consistent response formatting with ControllerResult pattern')
    .line()
    .import(['Request', 'Response', 'CookieOptions'], 'express')
    .import(['logger'], './logger.utils.js')
    .line()
    .section('Controller Result Types')
    .line()
    .line('export interface ResponseCookie {')
    .line('  name: string;')
    .line('  value: string;')
    .line('  options?: CookieOptions;')
    .line('}')
    .line()
    .line('export interface ControllerResult<T = any> {')
    .line('  success: boolean;')
    .line('  message: string;')
    .line('  data?: T;')
    .line('  error?: string;')
    .line('  details?: unknown;')
    .line('  statusCode?: number;')
    .line('  currentPage?: number;')
    .line('  totalPages?: number;')
    .line('  totalItems?: number;')
    .line('  totalCount?: number;')
    .line('  hasMorePages?: boolean;')
    .line('  cookies?: ResponseCookie[];')
    .line('}')
    .line()
    .line('type PaginationMeta = Pick<')
    .line('  ControllerResult,')
    .line("  'currentPage' | 'totalPages' | 'totalItems' | 'totalCount' | 'hasMorePages'")
    .line('>;')
    .line()
    .line('export const createResponse = {')
    .line('  success<T>(')
    .line('    message: string,')
    .line('    data?: T,')
    .line('    statusCode = 200,')
    .line('    pagination?: PaginationMeta,')
    .line('    cookies?: ResponseCookie[]')
    .line('  ): ControllerResult<T> {')
    .line('    return {')
    .line('      success: true,')
    .line('      message,')
    .line('      statusCode,')
    .line('      ...(pagination ?? {}),')
    .line('      ...(cookies && cookies.length > 0 ? { cookies } : {}),')
    .line('      data')
    .line('    };')
    .line('  },')
    .line()
    .line('  error(')
    .line('    message: string,')
    .line('    error: string = "Request error",')
    .line('    statusCode = 400,')
    .line('    details?: unknown')
    .line('  ): ControllerResult {')
    .line('    return {')
    .line('      success: false,')
    .line('      message,')
    .line('      error,')
    .line('      statusCode,')
    .line('      details')
    .line('    };')
    .line('  },')
    .line()
    .line('  unauthorized(')
    .line('    message = "Unauthorized",')
    .line('    error = "Authentication required"')
    .line('  ): ControllerResult {')
    .line('    return {')
    .line('      success: false,')
    .line('      message,')
    .line('      error,')
    .line('      statusCode: 401')
    .line('    };')
    .line('  },')
    .line()
    .line('  forbidden(')
    .line('    message = "Forbidden",')
    .line('    error = "Insufficient permissions"')
    .line('  ): ControllerResult {')
    .line('    return {')
    .line('      success: false,')
    .line('      message,')
    .line('      error,')
    .line('      statusCode: 403')
    .line('    };')
    .line('  },')
    .line()
    .line('  notFound(resource = "Resource"): ControllerResult {')
    .line('    return {')
    .line('      success: false,')
    .line('      message: resource + " not found",')
    .line("      error: 'NOT_FOUND',")
    .line('      statusCode: 404')
    .line('    };')
    .line('  },')
    .line()
    .line('  validation(')
    .line('    errors: ValidationError[] = [],')
    .line('    message = "Validation failed"')
    .line('  ): ControllerResult {')
    .line('    return {')
    .line('      success: false,')
    .line('      message,')
    .line("      error: 'VALIDATION_ERROR',")
    .line('      statusCode: 422,')
    .line('      details: errors')
    .line('    };')
    .line('  },')
    .line()
    .line('  custom<T>(result: ControllerResult<T>): ControllerResult<T> {')
    .line('    return result;')
    .line('  }')
    .line('};')
    .line()
    .line('export function createSuccessResult<T>(')
    .line('  message: string,')
    .line('  data?: T,')
    .line('  error?: string,')
    .line('  statusCode = 200,')
    .line('  currentPage?: number,')
    .line('  totalPages?: number,')
    .line('  totalItems?: number,')
    .line('  totalCount?: number,')
    .line('  hasMorePages?: boolean')
    .line('): ControllerResult<T> {')
    .line('  const response = createResponse.success(message, data, statusCode, {')
    .line('    currentPage,')
    .line('    totalPages,')
    .line('    totalItems,')
    .line('    totalCount,')
    .line('    hasMorePages')
    .line('  });')
    .line('  if (error) {')
    .line('    response.error = error;')
    .line('  }')
    .line('  return response;')
    .line('}')
    .line()
    .line('export function createErrorResult(')
    .line('  message: string,')
    .line('  error?: string,')
    .line('  statusCode = 400')
    .line('): ControllerResult {')
    .line('  return createResponse.error(message, error, statusCode);')
    .line('}')
    .line()
    .section('Validation Types')
    .line()
    .line('export interface ValidationError {')
    .line('  field: string;')
    .line('  message: string;')
    .line('}')
    .line()
    .line('export interface ValidationResult<T = unknown> {')
    .line('  isValid: boolean;')
    .line('  data?: T;')
    .line('  errors?: ValidationError[];')
    .line('}')
    .line()
    .line('export interface SendResponseOptions<')
    .line('  TValidation = unknown,')
    .line('  TResponse = unknown,')
    .line('> {')
    .line('  onSuccess?: (params: {')
    .line('    req: Request;')
    .line('    res: Response;')
    .line('    validData: TValidation;')
    .line('    controllerResult: ControllerResult<TResponse>;')
    .line('  }) => void | Promise<void>;')
    .line('}')
    .line()
    .line('type KataxIssue = {')
    .line('  path: (string | number)[];')
    .line('  message: string;')
    .line('};')
    .line()
    .line('type KataxSafeParseResult<T> =')
    .line('  | { success: true; data: T }')
    .line('  | { success: false; issues: KataxIssue[] };')
    .line()
    .line('export interface KataxSchema<T = unknown> {')
    .line('  safeParse(input: unknown): KataxSafeParseResult<T>;')
    .line('  safeParseAsync(input: unknown): Promise<KataxSafeParseResult<T>>;')
    .line('  hasAsyncValidation?: () => boolean;')
    .line('  _asyncValidators?: unknown[];')
    .line('}')
    .line()
    .comment('Generic reusable validator for katax-core schemas')
    .comment('Supports both sync and async validation automatically')
    .line('export async function validateSchema<T>(')
    .line('  schema: KataxSchema<T>,')
    .line('  data: unknown')
    .line('): Promise<ValidationResult<T>> {')
    .line('  const hasAsyncValidators =')
    .line("    typeof schema.hasAsyncValidation === 'function'")
    .line('      ? schema.hasAsyncValidation()')
    .line('      : !!(schema._asyncValidators && schema._asyncValidators.length > 0);')
    .line()
    .line('  let result: KataxSafeParseResult<T>;')
    .line('  try {')
    .line('    if (hasAsyncValidators) {')
    .line('      result = await schema.safeParseAsync(data);')
    .line('    } else {')
    .line('      result = schema.safeParse(data);')
    .line('    }')
    .line('  } catch (error) {')
    .line("    return { isValid: false, errors: [{ field: 'unknown', message: 'Unexpected validation error' }] };")
    .line('  }')
    .line()
    .line('  if (!result.success) {')
    .line('    const errors = result.issues.map((issue) => ({')
    .line("      field: issue.path.join('.') || 'root',")
    .line('      message: issue.message')
    .line('    }));')
    .line('    return { isValid: false, errors };')
    .line('  }')
    .line()
    .line('  return { isValid: true, data: result.data };')
    .line('}')
    .line()
    .section('sendResponse Pipeline')
    .line()
    .comment('Advanced: Send response with validation + controller pipeline')
    .comment('1. Validates request data 2. Executes controller 3. Sends HTTP response with cookie support')
    .line('export async function sendResponse<TValidation = unknown, TResponse = unknown>(')
    .line('  req: Request,')
    .line('  res: Response,')
    .line('  validator: () => Promise<ValidationResult<TValidation>>,')
    .line('  controller: (validData: TValidation) => Promise<ControllerResult<TResponse>>,')
    .line('  options?: SendResponseOptions<TValidation, TResponse>')
    .line('): Promise<void> {')
    .line('  try {')
    .line('    // 1. Execute validation')
    .line('    const validationResult = await validator();')
    .line()
    .line('    if (!validationResult.isValid) {')
    .line('      logger.warn({ method: req.method, path: req.path, errors: validationResult.errors, message: "Validation failed" });')
    .line('      const validationResponse = createResponse.validation(')
    .line('        validationResult.errors || [],')
    .line('        "Invalid data"')
    .line('      );')
    .line('      res.status(validationResponse.statusCode || 422).json(validationResponse);')
    .line('      return;')
    .line('    }')
    .line()
    .line('    // 2. Execute controller if validation passes')
    .line('    const controllerResult = await controller(validationResult.data as TValidation);')
    .line()
    .line('    // 2a. Apply cookies from controller result')
    .line('    if (controllerResult.cookies && controllerResult.cookies.length > 0) {')
    .line('      for (const cookie of controllerResult.cookies) {')
    .line('        if (cookie.options) {')
    .line('          res.cookie(cookie.name, cookie.value, cookie.options);')
    .line('        } else {')
    .line('          res.cookie(cookie.name, cookie.value);')
    .line('        }')
    .line('      }')
    .line('    }')
    .line()
    .line('    if (controllerResult.success && options?.onSuccess) {')
    .line('      await options.onSuccess({')
    .line('        req,')
    .line('        res,')
    .line('        validData: validationResult.data as TValidation,')
    .line('        controllerResult,')
    .line('      });')
    .line('    }')
    .line()
    .line('    // 3. Build HTTP response')
    .line('    const statusCode = controllerResult.statusCode || (controllerResult.success ? 200 : 400);')
    .line()
    .line('    interface ResponsePayload {')
    .line('      success: boolean;')
    .line('      message: string;')
    .line('      error?: string;')
    .line('      totalItems?: number;')
    .line('      totalCount?: number;')
    .line('      currentPage?: number;')
    .line('      totalPages?: number;')
    .line('      hasMorePages?: boolean;')
    .line('      data?: TResponse;')
    .line('    }')
    .line()
    .line('    const response: ResponsePayload = {')
    .line('      success: controllerResult.success,')
    .line('      message: controllerResult.message')
    .line('    };')
    .line()
    .line('    if (controllerResult.error) {')
    .line('      response.error = controllerResult.error;')
    .line('    }')
    .line()
    .line('    if (controllerResult.totalItems !== undefined) {')
    .line('      response.totalItems = controllerResult.totalItems;')
    .line('    }')
    .line()
    .line('    if (controllerResult.totalCount !== undefined) {')
    .line('      response.totalCount = controllerResult.totalCount;')
    .line('    }')
    .line()
    .line('    if (controllerResult.currentPage !== undefined) {')
    .line('      response.currentPage = controllerResult.currentPage;')
    .line('    }')
    .line()
    .line('    if (controllerResult.totalPages !== undefined) {')
    .line('      response.totalPages = controllerResult.totalPages;')
    .line('    }')
    .line()
    .line('    if (controllerResult.hasMorePages !== undefined) {')
    .line('      response.hasMorePages = controllerResult.hasMorePages;')
    .line('    }')
    .line()
    .line('    if (controllerResult.data !== undefined) {')
    .line('      response.data = controllerResult.data;')
    .line('    }')
    .line()
    .line('    res.status(statusCode).json(response);')
    .line('  } catch (error) {')
    .line('    logger.error({ err: error, method: req.method, path: req.path, message: "Internal server error" });')
    .line('    res.status(500).json({')
    .line('      ...createResponse.error(')
    .line('        "Internal server error",')
    .line('        error instanceof Error ? error.message : "Unknown error",')
    .line('        500')
    .line('      )')
    .line('    });')
    .line('  }')
    .line('}')
    .line()
    .section('Cookie Helpers')
    .line()
    .line('export function setCookie(')
    .line('  res: Response,')
    .line('  name: string,')
    .line('  value: string,')
    .line('  options?: CookieOptions')
    .line('): void {')
    .line('  res.cookie(name, value, options);')
    .line('}')
    .line()
    .line('export function clearCookie(')
    .line('  res: Response,')
    .line('  name: string,')
    .line('  options?: CookieOptions')
    .line('): void {')
    .line('  res.clearCookie(name, options);')
    .line('}');

  return builder.build();
}
