/**
 * Stream utilities template generator
 * Creates helper functions for streaming responses (SSE, chunked transfer)
 */

import { CodeBuilder } from "../base/code-builder.js";

export function generateStreamUtils(): string {
  const builder = new CodeBuilder();

  builder
    .comment("Stream Response Utilities")
    .comment("Server-Sent Events (SSE) and streaming responses")
    .line()
    .import(["Request", "Response"], "express")
    .import(["logger"], "./logger.utils.js")
    .line()
    .section("Server-Sent Events (SSE)")
    .line()
    .comment("Initialize SSE connection with proper headers")
    .line("export function initSSE(res: Response): void {")
    .line('  res.setHeader("Content-Type", "text/event-stream");')
    .line('  res.setHeader("Cache-Control", "no-cache");')
    .line('  res.setHeader("Connection", "keep-alive");')
    .line(
      '  res.setHeader("X-Accel-Buffering", "no"); // Disable nginx buffering',
    )
    .line("  res.flushHeaders();")
    .line("}")
    .line()
    .comment("Send SSE event")
    .line("export function sendSSEEvent(")
    .line("  res: Response,")
    .line("  data: any,")
    .line("  event?: string,")
    .line("  id?: string")
    .line("): boolean {")
    .line("  try {")
    .line("    if (id) {")
    .line("      res.write(`id: ${id}\\n`);")
    .line("    }")
    .line("    if (event) {")
    .line("      res.write(`event: ${event}\\n`);")
    .line("    }")
    .line("    res.write(`data: ${JSON.stringify(data)}\\n\\n`);")
    .line("    return true;")
    .line("  } catch (error) {")
    .line(
      '    logger.error({ message: "Failed to send SSE event", err: error });',
    )
    .line("    return false;")
    .line("  }")
    .line("}")
    .line()
    .comment("Send SSE comment (keeps connection alive)")
    .line(
      'export function sendSSEComment(res: Response, comment: string = "ping"): boolean {',
    )
    .line("  try {")
    .line("    res.write(`: ${comment}\\n\\n`);")
    .line("    return true;")
    .line("  } catch (error) {")
    .line("    return false;")
    .line("  }")
    .line("}")
    .line()
    .comment("Close SSE connection gracefully")
    .line("export function closeSSE(res: Response): void {")
    .line("  try {")
    .line('    res.write("event: close\\n");')
    .line('    res.write("data: {}\\n\\n");')
    .line("    res.end();")
    .line("  } catch (error) {")
    .line(
      '    logger.error({ message: "Failed to close SSE connection", err: error });',
    )
    .line("  }")
    .line("}")
    .line()
    .section("SSE Stream Manager")
    .line()
    .comment("Manages SSE connection with automatic cleanup")
    .line("export class SSEStream {")
    .line("  private closed = false;")
    .line("  private keepAliveInterval?: NodeJS.Timeout;")
    .line()
    .line("  constructor(")
    .line("    private res: Response,")
    .line("    private keepAliveMs: number = 30000")
    .line("  ) {")
    .line("    initSSE(res);")
    .line("    this.setupKeepAlive();")
    .line("    this.setupCleanup();")
    .line("  }")
    .line()
    .line("  private setupKeepAlive(): void {")
    .line("    this.keepAliveInterval = setInterval(() => {")
    .line("      if (!this.closed) {")
    .line("        sendSSEComment(this.res);")
    .line("      }")
    .line("    }, this.keepAliveMs);")
    .line("  }")
    .line()
    .line("  private setupCleanup(): void {")
    .line('    this.res.on("close", () => {')
    .line("      this.close();")
    .line("    });")
    .line("  }")
    .line()
    .line("  send(data: any, event?: string, id?: string): boolean {")
    .line("    if (this.closed) return false;")
    .line("    return sendSSEEvent(this.res, data, event, id);")
    .line("  }")
    .line()
    .line("  sendError(error: Error | string): boolean {")
    .line('    const errorData = typeof error === "string"')
    .line("      ? { message: error }")
    .line("      : { message: error.message, stack: error.stack };")
    .line('    return this.send(errorData, "error");')
    .line("  }")
    .line()
    .line("  close(): void {")
    .line("    if (this.closed) return;")
    .line("    this.closed = true;")
    .line("    if (this.keepAliveInterval) {")
    .line("      clearInterval(this.keepAliveInterval);")
    .line("    }")
    .line("    closeSSE(this.res);")
    .line("  }")
    .line()
    .line("  isClosed(): boolean {")
    .line("    return this.closed;")
    .line("  }")
    .line("}")
    .line()
    .section("Chunked Transfer Encoding")
    .line()
    .comment("Send chunked response - useful for large data")
    .line("export function sendChunked(")
    .line("  res: Response,")
    .line("  data: any,")
    .line("  options?: {")
    .line("    contentType?: string;")
    .line("    headers?: Record<string, string>;")
    .line("  }")
    .line("): void {")
    .line('  const contentType = options?.contentType || "application/json";')
    .line('  res.setHeader("Content-Type", contentType);')
    .line('  res.setHeader("Transfer-Encoding", "chunked");')
    .line()
    .line("  if (options?.headers) {")
    .line("    Object.entries(options.headers).forEach(([key, value]) => {")
    .line("      res.setHeader(key, value);")
    .line("    });")
    .line("  }")
    .line()
    .line(
      '  const chunk = typeof data === "string" ? data : JSON.stringify(data);',
    )
    .line("  res.write(chunk);")
    .line("  res.end();")
    .line("}")
    .line()
    .comment("Stream async iterator - sends data as it becomes available")
    .line("export async function streamAsyncIterator<T>(")
    .line("  res: Response,")
    .line("  iterator: AsyncIterable<T>,")
    .line("  options?: {")
    .line("    transform?: (item: T) => any;")
    .line("    onError?: (error: Error) => void;")
    .line("    contentType?: string;")
    .line("  }")
    .line("): Promise<void> {")
    .line("  try {")
    .line(
      '    const contentType = options?.contentType || "application/x-ndjson";',
    )
    .line('    res.setHeader("Content-Type", contentType);')
    .line('    res.setHeader("Transfer-Encoding", "chunked");')
    .line()
    .line("    for await (const item of iterator) {")
    .line(
      "      const data = options?.transform ? options.transform(item) : item;",
    )
    .line('      const chunk = JSON.stringify(data) + "\\n";')
    .line("      res.write(chunk);")
    .line("    }")
    .line()
    .line("    res.end();")
    .line("  } catch (error) {")
    .line("    if (options?.onError) {")
    .line("      options.onError(error as Error);")
    .line("    }")
    .line('    logger.error({ message: "Stream error", err: error });')
    .line("    if (!res.headersSent) {")
    .line('      res.status(500).json({ error: "Stream failed" });')
    .line("    }")
    .line("  }")
    .line("}")
    .line()
    .comment("Stream array in chunks - useful for paginated data")
    .line("export async function streamArray<T>(")
    .line("  res: Response,")
    .line("  items: T[],")
    .line("  chunkSize: number = 100,")
    .line("  delayMs: number = 0")
    .line("): Promise<void> {")
    .line('  res.setHeader("Content-Type", "application/json");')
    .line('  res.setHeader("Transfer-Encoding", "chunked");')
    .line()
    .line('  res.write("[");')
    .line()
    .line("  for (let i = 0; i < items.length; i += chunkSize) {")
    .line("    const chunk = items.slice(i, i + chunkSize);")
    .line('    const json = chunk.map(item => JSON.stringify(item)).join(",");')
    .line('    res.write(i === 0 ? json : "," + json);')
    .line()
    .line("    if (delayMs > 0 && i + chunkSize < items.length) {")
    .line("      await new Promise(resolve => setTimeout(resolve, delayMs));")
    .line("    }")
    .line("  }")
    .line()
    .line('  res.write("]");')
    .line("  res.end();")
    .line("}")
    .line()
    .section("Example Usage")
    .line()
    .comment("Example: SSE endpoint")
    .comment(
      "export async function streamEventsHandler(req: Request, res: Response) {",
    )
    .comment("  const stream = new SSEStream(res);")
    .comment("")
    .comment("  try {")
    .comment("    for (let i = 0; i < 10; i++) {")
    .comment(
      '      stream.send({ count: i, timestamp: Date.now() }, "update");',
    )
    .comment("      await new Promise(resolve => setTimeout(resolve, 1000));")
    .comment("    }")
    .comment("    stream.close();")
    .comment("  } catch (error) {")
    .comment("    stream.sendError(error as Error);")
    .comment("    stream.close();")
    .comment("  }")
    .comment("}")
    .line()
    .comment("Example: Stream database results")
    .comment(
      "export async function streamUsersHandler(req: Request, res: Response) {",
    )
    .comment('  const users = await db.query("SELECT * FROM users");')
    .comment("  await streamArray(res, users, 50);")
    .comment("}");

  return builder.toString();
}
