import inquirer from "inquirer";
import ora from "ora";
import path from "path";
import fs from "fs/promises";
import { success, error, gray, title, info, warning } from "../utils/logger.js";
import {
  ensureDir,
  fileExists,
  toCamelCase,
  toPascalCase,
  writeFile,
} from "../utils/file-utils.js";

type SupportedDatabase = "postgresql" | "mysql" | "mongodb";
type IdType = "string" | "number";

interface GenerateRepositoryOptions {
  database?: SupportedDatabase;
  table?: string;
  collection?: string;
  dbName?: string;
  idType?: IdType;
}

interface ResourceNaming {
  segments: string[];
  basePath: string;
  lowerName: string;
  camelName: string;
  pascalName: string;
  relativePath: string;
}

function resolveResourceNaming(input: string): ResourceNaming {
  const segments = input
    .split("/")
    .map((segment) => segment.trim().toLowerCase())
    .filter(Boolean);

  if (segments.length === 0) {
    throw new Error("Repository name is required");
  }

  const lowerName = segments[segments.length - 1] as string;
  const joinedForCase = segments.join("-");

  return {
    segments,
    basePath: path.join(process.cwd(), "src", "api", ...segments),
    lowerName,
    camelName: toCamelCase(joinedForCase),
    pascalName: toPascalCase(joinedForCase),
    relativePath: `src/api/${segments.join("/")}/${lowerName}.repository.ts`,
  };
}

function detectDatabaseFromPackageJson(
  pkg: Record<string, unknown>,
): SupportedDatabase | null {
  const deps = (pkg.dependencies ?? {}) as Record<string, string>;
  const devDeps = (pkg.devDependencies ?? {}) as Record<string, string>;

  const hasPg = Boolean(deps.pg || devDeps.pg);
  const hasMysql = Boolean(deps.mysql2 || devDeps.mysql2);
  const hasMongo = Boolean(deps.mongodb || devDeps.mongodb);

  if (hasPg) return "postgresql";
  if (hasMysql) return "mysql";
  if (hasMongo) return "mongodb";
  return null;
}

function generateSqlRepositoryTemplate(config: {
  pascalName: string;
  idType: IdType;
  tableName: string;
  dbName: string;
  isPostgres: boolean;
}): string {
  const { pascalName, idType, tableName, dbName, isPostgres } = config;
  const idParam = isPostgres ? "$1" : "?";
  const createImplementation = isPostgres
    ? `const placeholders = values.map((_, i) => '$' + (i + 1)).join(', ');

    const sql =
      'INSERT INTO ' +
      this.tableName +
      ' (' +
      columns.join(', ') +
      ') VALUES (' +
      placeholders +
      ') RETURNING *';

    const rows = await this.db.query<${pascalName}Record[]>(sql, values);
    return rows[0] as ${pascalName}Record;`
    : `const placeholders = values.map(() => '?').join(', ');

    const sql =
      'INSERT INTO ' +
      this.tableName +
      ' (' +
      columns.join(', ') +
      ') VALUES (' +
      placeholders +
      ')';

    const result = await this.db.query<SqlWriteResult>(sql, values);

    const insertedId = result.insertId as ${pascalName}Id;
    const created = await this.findById(insertedId);

    if (!created) {
      throw new Error('Failed to load created record');
    }

    return created;`;

  const updateImplementation = isPostgres
    ? `const setClause = entries.map(([key], i) => key + ' = $' + (i + 1)).join(', ');
    const sql =
      'UPDATE ' +
      this.tableName +
      ' SET ' +
      setClause +
      ' WHERE id = $' +
      (entries.length + 1) +
      ' RETURNING *';

    const rows = await this.db.query<${pascalName}Record[]>(sql, [...values, id]);

    if (!rows[0]) {
      throw new Error('Record with id ' + String(id) + ' was not found');
    }

    return rows[0];`
    : `const setClause = entries.map(([key]) => key + ' = ?').join(', ');
    const sql = 'UPDATE ' + this.tableName + ' SET ' + setClause + ' WHERE id = ?';

    const result = await this.db.query<SqlWriteResult>(sql, [...values, id]);

    if ((result.affectedRows ?? 0) === 0) {
      throw new Error('Record with id ' + String(id) + ' was not found');
    }

    const updated = await this.findById(id);

    if (!updated) {
      throw new Error('Record with id ' + String(id) + ' was not found');
    }

    return updated;`;

  return `import { katax } from 'katax-service-manager';
import type { ISqlDatabase } from 'katax-service-manager';

export type ${pascalName}Id = ${idType};

export interface ${pascalName}Record {
  id: ${pascalName}Id;
  [key: string]: unknown;
}

interface SqlWriteResult {
  rowCount?: number;
  affectedRows?: number;
  insertId?: number;
}

/**
 * ${pascalName} repository generated by katax-cli
 *
 * NOTE:
 * - This template is intentionally conservative and compiles out-of-the-box.
 * - Replace SELECT * with explicit columns once your schema is defined.
 */
export class ${pascalName}Repository {
  constructor(
    private readonly tableName: string = '${tableName}',
    private readonly dbName: string = '${dbName}'
  ) {}

  private get db(): ISqlDatabase {
    const db = katax.db(this.dbName);
    const dbType = db.config?.type;

    if (dbType !== 'postgresql' && dbType !== 'mysql') {
      throw new Error(
        'Repository ' +
          '${pascalName}Repository' +
          ' requires a SQL connection (postgresql/mysql), got ' +
          String(dbType)
      );
    }

    if (!db.query) {
      throw new Error('Database connection does not expose query()');
    }

    return db as ISqlDatabase;
  }

  async findAll(): Promise<${pascalName}Record[]> {
    return this.db.query<${pascalName}Record[]>(
      \`SELECT * FROM \${this.tableName} ORDER BY id DESC\`
    );
  }

  async findById(id: ${pascalName}Id): Promise<${pascalName}Record | null> {
    const rows = await this.db.query<${pascalName}Record[]>(
      \`SELECT * FROM \${this.tableName} WHERE id = ${idParam} LIMIT 1\`,
      [id]
    );

    return rows[0] ?? null;
  }

  async exists(id: ${pascalName}Id): Promise<boolean> {
    const rows = await this.db.query<Array<{ count: string | number }>>(
      \`SELECT COUNT(*) AS count FROM \${this.tableName} WHERE id = ${idParam}\`,
      [id]
    );

    const count = Number(rows[0]?.count ?? 0);
    return count > 0;
  }

  async create(data: Omit<${pascalName}Record, 'id'>): Promise<${pascalName}Record> {
    const entries = Object.entries(data);

    if (entries.length === 0) {
      throw new Error('create() requires at least one field');
    }

    const columns = entries.map(([key]) => key);
    const values = entries.map(([, value]) => value);

    ${createImplementation}
  }

  async update(id: ${pascalName}Id, data: Partial<Omit<${pascalName}Record, 'id'>>): Promise<${pascalName}Record> {
    const entries = Object.entries(data);

    if (entries.length === 0) {
      throw new Error('update() requires at least one field');
    }

    const values = entries.map(([, value]) => value);

    ${updateImplementation}
  }

  async delete(id: ${pascalName}Id): Promise<boolean> {
    const result = await this.db.query<SqlWriteResult>(
      \`DELETE FROM \${this.tableName} WHERE id = ${idParam}\`,
      [id]
    );

    const affected = result.rowCount ?? result.affectedRows ?? 0;
    return affected > 0;
  }
}
`;
}

function generateMongoRepositoryTemplate(config: {
  pascalName: string;
  idType: IdType;
  collectionName: string;
  dbName: string;
  mongoDatabaseName: string;
}): string {
  const { pascalName, idType, collectionName, dbName, mongoDatabaseName } =
    config;

  return `import { katax } from 'katax-service-manager';
import type { IMongoDatabase } from 'katax-service-manager';

export type ${pascalName}Id = ${idType};

export interface ${pascalName}Record {
  _id: ${pascalName}Id;
  [key: string]: unknown;
}

interface MongoCollectionLike<T extends Record<string, unknown>> {
  find(query: Record<string, unknown>): { toArray(): Promise<T[]> };
  findOne(query: Record<string, unknown>): Promise<T | null>;
  insertOne(doc: Record<string, unknown>): Promise<{ insertedId: unknown }>;
  updateOne(
    filter: Record<string, unknown>,
    update: Record<string, unknown>
  ): Promise<{ matchedCount: number }>;
  deleteOne(filter: Record<string, unknown>): Promise<{ deletedCount: number }>;
  countDocuments(filter: Record<string, unknown>): Promise<number>;
}

interface MongoClientLike {
  db(name?: string): {
    collection<T extends Record<string, unknown>>(name: string): MongoCollectionLike<T>;
  };
}

/**
 * ${pascalName} repository generated by katax-cli
 *
 * NOTE:
 * - For ObjectId-based schemas, map string IDs to ObjectId in this file.
 */
export class ${pascalName}Repository {
  constructor(
    private readonly collectionName: string = '${collectionName}',
    private readonly dbName: string = '${dbName}',
    private readonly mongoDatabaseName: string = '${mongoDatabaseName}'
  ) {}

  private async getCollection(): Promise<MongoCollectionLike<${pascalName}Record>> {
    const dbConnection = katax.db(this.dbName);
    const dbType = dbConnection.config?.type;

    if (dbType !== 'mongodb') {
      throw new Error(
        'Repository ' +
          '${pascalName}Repository' +
          ' requires a mongodb connection, got ' +
          String(dbType)
      );
    }

    const db = dbConnection as IMongoDatabase;
    const client = (await db.getClient()) as MongoClientLike;

    return client
      .db(this.mongoDatabaseName)
      .collection<${pascalName}Record>(this.collectionName);
  }

  async findAll(): Promise<${pascalName}Record[]> {
    const collection = await this.getCollection();
    return collection.find({}).toArray();
  }

  async findById(id: ${pascalName}Id): Promise<${pascalName}Record | null> {
    const collection = await this.getCollection();
    return collection.findOne({ _id: id });
  }

  async exists(id: ${pascalName}Id): Promise<boolean> {
    const collection = await this.getCollection();
    const count = await collection.countDocuments({ _id: id });
    return count > 0;
  }

  async create(data: Omit<${pascalName}Record, '_id'>): Promise<${pascalName}Record> {
    const collection = await this.getCollection();
    const result = await collection.insertOne(data as Record<string, unknown>);

    const created = await this.findById(result.insertedId as ${pascalName}Id);
    if (!created) {
      throw new Error('Failed to load created record');
    }

    return created;
  }

  async update(id: ${pascalName}Id, data: Partial<Omit<${pascalName}Record, '_id'>>): Promise<${pascalName}Record> {
    const collection = await this.getCollection();
    const result = await collection.updateOne({ _id: id }, { $set: data as Record<string, unknown> });

    if (result.matchedCount === 0) {
      throw new Error(\`Record with id \${id} was not found\`);
    }

    const updated = await this.findById(id);
    if (!updated) {
      throw new Error(\`Record with id \${id} was not found\`);
    }

    return updated;
  }

  async delete(id: ${pascalName}Id): Promise<boolean> {
    const collection = await this.getCollection();
    const result = await collection.deleteOne({ _id: id });
    return result.deletedCount > 0;
  }
}
`;
}

export async function generateRepositoryCommand(
  name: string,
  options: GenerateRepositoryOptions = {},
) {
  const resource = resolveResourceNaming(name);
  title(`📦 Generate Repository: ${name}`);

  const packageJsonPath = path.join(process.cwd(), "package.json");
  if (!fileExists(packageJsonPath)) {
    error("Not in a project directory!");
    gray("Run this command from your project root\n");
    process.exit(1);
  }

  const packageJson = JSON.parse(
    await fs.readFile(packageJsonPath, "utf-8"),
  ) as Record<string, unknown>;

  const inferredDatabase = detectDatabaseFromPackageJson(packageJson);

  const questions: any[] = [
    {
      type: "list",
      name: "database",
      message: "Database type for this repository:",
      choices: [
        { name: "PostgreSQL", value: "postgresql" },
        { name: "MySQL", value: "mysql" },
        { name: "MongoDB", value: "mongodb" },
      ],
      default: options.database ?? inferredDatabase ?? "postgresql",
    },
    {
      type: "list",
      name: "idType",
      message: "ID type:",
      choices: [
        { name: "string", value: "string" },
        { name: "number", value: "number" },
      ],
      default: options.idType ?? "string",
    },
    {
      type: "input",
      name: "dbName",
      message: "Katax database connection name:",
      default: options.dbName ?? "main",
      validate: (input: string) =>
        input.trim().length > 0 ? true : "db name is required",
    },
    {
      type: "input",
      name: "tableOrCollection",
      message: "Table/collection name:",
      default: options.table ?? options.collection ?? `${resource.lowerName}s`,
      validate: (input: string) =>
        input.trim().length > 0 ? true : "table/collection name is required",
    },
    {
      type: "input",
      name: "mongoDatabaseName",
      message: "MongoDB database name:",
      default: "app",
      when: (input: { database: SupportedDatabase }) =>
        input.database === "mongodb",
      validate: (input: string) =>
        input.trim().length > 0 ? true : "mongo database name is required",
    },
  ];

  const answers = await inquirer.prompt(questions);

  const database = answers.database as SupportedDatabase;
  const idType = answers.idType as IdType;
  const dbName = (answers.dbName as string).trim();
  const tableOrCollection = (answers.tableOrCollection as string).trim();
  const mongoDatabaseName = (
    (answers.mongoDatabaseName as string | undefined) ?? "app"
  ).trim();

  const spinner = ora("Generating repository file...").start();

  try {
    await ensureDir(resource.basePath);

    const outputPath = path.join(
      resource.basePath,
      `${resource.lowerName}.repository.ts`,
    );
    if (fileExists(outputPath)) {
      spinner.stop();
      warning(`Repository already exists: ${resource.relativePath}`);
      gray("Use a different name or remove the existing file first.\n");
      return;
    }

    const content =
      database === "mongodb"
        ? generateMongoRepositoryTemplate({
            pascalName: resource.pascalName,
            idType,
            collectionName: tableOrCollection,
            dbName,
            mongoDatabaseName,
          })
        : generateSqlRepositoryTemplate({
            pascalName: resource.pascalName,
            idType,
            tableName: tableOrCollection,
            dbName,
            isPostgres: database === "postgresql",
          });

    await writeFile(outputPath, content);

    spinner.succeed("Repository generated");

    success(`\n✨ Repository \"${name}\" created successfully!\n`);
    info("Generated file:");
    gray(`  ${resource.relativePath}\n`);

    info("Next steps:");
    gray(
      `  1. Import ${resource.pascalName}Repository in your controller/handler and instantiate it.`,
    );
    gray("  2. Replace broad SELECT * statements with explicit columns.");
    if (database === "mongodb") {
      gray(
        "  3. If you use ObjectId, convert incoming string IDs before querying.",
      );
    }
    console.log();
  } catch (err) {
    spinner.fail("Failed to generate repository");
    error(err instanceof Error ? err.message : "Unknown error");
    process.exit(1);
  }
}

export const __repositoryTestUtils = {
  resolveResourceNaming,
  detectDatabaseFromPackageJson,
  generateSqlRepositoryTemplate,
  generateMongoRepositoryTemplate,
};
